// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/mcq": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/mcq";
  };
  "routes/question.tsx": {
    id: "routes/question";
    page: "/";
  };
  "routes/mcq.tsx": {
    id: "routes/mcq";
    page: "/mcq";
  };
};